var brand = 'bad practice';
let counter = 100;
const token = "123WQDQWS";

console.log(counter);

// individual line comment 

/*
     many lines comment 
*/

// interpolacion

let interpolation = `el valor de counter es| ${counter}`;
console.log("interpolation");
console.log("interpolation", counter);
console.log("interpolation", + counter);

// MOKAR0O TO CREATE DATA 


const persons = [{
    "id": 1,
    "first_name": "Liuka",
    "last_name": "Pickton",
    "email": "lpickton0@pagesperso-orange.fr",
    "gender": "Female"
  }, {
    "id": 2,
    "first_name": "Archie",
    "last_name": "Hazeman",
    "email": "ahazeman1@stumbleupon.com",
    "gender": "Male"
  }, {
    "id": 3,
    "first_name": "Mag",
    "last_name": "Papierz",
    "email": "mpapierz2@blinklist.com",
    "gender": "Female"
  }, {
    "id": 4,
    "first_name": "Caralie",
    "last_name": "Glencrash",
    "email": "cglencrash3@yolasite.com",
    "gender": "Genderqueer"
  }, {
    "id": 5,
    "first_name": "Roth",
    "last_name": "Shama",
    "email": "rshama4@washingtonpost.com",
    "gender": "Genderfluid"
  }, {
    "id": 6,
    "first_name": "Janis",
    "last_name": "Tanby",
    "email": "jtanby5@harvard.edu",
    "gender": "Female"
  }, {
    "id": 7,
    "first_name": "Huntington",
    "last_name": "Itzkovwitch",
    "email": "hitzkovwitch6@mashable.com",
    "gender": "Non-binary"
  }, {
    "id": 8,
    "first_name": "Addi",
    "last_name": "Standish-Brooks",
    "email": "astandishbrooks7@ucoz.ru",
    "gender": "Female"
  }, {
    "id": 9,
    "first_name": "Alfonso",
    "last_name": "Maund",
    "email": "amaund8@gravatar.com",
    "gender": "Male"
  }, {
    "id": 10,
    "first_name": "Kara-lynn",
    "last_name": "Josh",
    "email": "kjosh9@virginia.edu",
    "gender": "Female"
  }, {
    "id": 11,
    "first_name": "Emmye",
    "last_name": "Rozea",
    "email": "erozeaa@github.com",
    "gender": "Female"
  }, {
    "id": 12,
    "first_name": "Mignonne",
    "last_name": "Reolfi",
    "email": "mreolfib@telegraph.co.uk",
    "gender": "Female"
  }, {
    "id": 13,
    "first_name": "Deny",
    "last_name": "Tedahl",
    "email": "dtedahlc@google.co.jp",
    "gender": "Female"
  }, {
    "id": 14,
    "first_name": "Cornell",
    "last_name": "Wain",
    "email": "cwaind@joomla.org",
    "gender": "Male"
  }, {
    "id": 15,
    "first_name": "Rickey",
    "last_name": "Castaneda",
    "email": "rcastanedae@last.fm",
    "gender": "Bigender"
  }, {
    "id": 16,
    "first_name": "Modestine",
    "last_name": "Little",
    "email": "mlittlef@economist.com",
    "gender": "Female"
  }, {
    "id": 17,
    "first_name": "Ricoriki",
    "last_name": "Roffey",
    "email": "rroffeyg@naver.com",
    "gender": "Male"
  }, {
    "id": 18,
    "first_name": "Jaquith",
    "last_name": "Crookshank",
    "email": "jcrookshankh@samsung.com",
    "gender": "Female"
  }, {
    "id": 19,
    "first_name": "Urbain",
    "last_name": "Adacot",
    "email": "uadacoti@vk.com",
    "gender": "Male"
  }, {
    "id": 20,
    "first_name": "Anselm",
    "last_name": "Whyler",
    "email": "awhylerj@pagesperso-orange.fr",
    "gender": "Male"
  }, {
    "id": 21,
    "first_name": "Stefan",
    "last_name": "Costan",
    "email": "scostank@mail.ru",
    "gender": "Non-binary"
  }, {
    "id": 22,
    "first_name": "Cherice",
    "last_name": "Calbert",
    "email": "ccalbertl@dailymotion.com",
    "gender": "Female"
  }, {
    "id": 23,
    "first_name": "Artie",
    "last_name": "Schach",
    "email": "aschachm@dion.ne.jp",
    "gender": "Male"
  }, {
    "id": 24,
    "first_name": "Elaina",
    "last_name": "Sent",
    "email": "esentn@myspace.com",
    "gender": "Female"
  }, {
    "id": 25,
    "first_name": "Donella",
    "last_name": "Bickley",
    "email": "dbickleyo@deviantart.com",
    "gender": "Female"
  }, {
    "id": 26,
    "first_name": "Deva",
    "last_name": "Plumb",
    "email": "dplumbp@usda.gov",
    "gender": "Female"
  }, {
    "id": 27,
    "first_name": "Melany",
    "last_name": "Roj",
    "email": "mrojq@home.pl",
    "gender": "Female"
  }, {
    "id": 28,
    "first_name": "Paddie",
    "last_name": "Besnardeau",
    "email": "pbesnardeaur@si.edu",
    "gender": "Male"
  }, {
    "id": 29,
    "first_name": "Herbie",
    "last_name": "Jerrim",
    "email": "hjerrims@nature.com",
    "gender": "Male"
  }, {
    "id": 30,
    "first_name": "Enid",
    "last_name": "Lowthian",
    "email": "elowthiant@a8.net",
    "gender": "Female"
  }, {
    "id": 31,
    "first_name": "Rozanne",
    "last_name": "Dufoure",
    "email": "rdufoureu@theatlantic.com",
    "gender": "Female"
  }, {
    "id": 32,
    "first_name": "Celisse",
    "last_name": "Silversmidt",
    "email": "csilversmidtv@cnn.com",
    "gender": "Female"
  }, {
    "id": 33,
    "first_name": "Marchall",
    "last_name": "Cooch",
    "email": "mcoochw@disqus.com",
    "gender": "Male"
  }, {
    "id": 34,
    "first_name": "Pall",
    "last_name": "Heliot",
    "email": "pheliotx@i2i.jp",
    "gender": "Male"
  }, {
    "id": 35,
    "first_name": "Boote",
    "last_name": "Eglaise",
    "email": "beglaisey@uol.com.br",
    "gender": "Male"
  }, {
    "id": 36,
    "first_name": "Rowe",
    "last_name": "Jurasz",
    "email": "rjuraszz@istockphoto.com",
    "gender": "Female"
  }, {
    "id": 37,
    "first_name": "Meggie",
    "last_name": "Gasnoll",
    "email": "mgasnoll10@usnews.com",
    "gender": "Female"
  }, {
    "id": 38,
    "first_name": "Ginelle",
    "last_name": "Bavage",
    "email": "gbavage11@dropbox.com",
    "gender": "Female"
  }, {
    "id": 39,
    "first_name": "Sheelagh",
    "last_name": "Throssell",
    "email": "sthrossell12@mac.com",
    "gender": "Female"
  }, {
    "id": 40,
    "first_name": "Libby",
    "last_name": "Aasaf",
    "email": "laasaf13@studiopress.com",
    "gender": "Female"
  }, {
    "id": 41,
    "first_name": "Jodi",
    "last_name": "Nelius",
    "email": "jnelius14@e-recht24.de",
    "gender": "Male"
  }, {
    "id": 42,
    "first_name": "Dominique",
    "last_name": "Brugsma",
    "email": "dbrugsma15@soup.io",
    "gender": "Female"
  }, {
    "id": 43,
    "first_name": "Ellwood",
    "last_name": "Goulborn",
    "email": "egoulborn16@networksolutions.com",
    "gender": "Male"
  }, {
    "id": 44,
    "first_name": "Jobyna",
    "last_name": "Colls",
    "email": "jcolls17@cam.ac.uk",
    "gender": "Female"
  }, {
    "id": 45,
    "first_name": "Paquito",
    "last_name": "Stockle",
    "email": "pstockle18@reddit.com",
    "gender": "Male"
  }, {
    "id": 46,
    "first_name": "Danica",
    "last_name": "Ibbeson",
    "email": "dibbeson19@php.net",
    "gender": "Female"
  }, {
    "id": 47,
    "first_name": "Lorraine",
    "last_name": "Dobrowolny",
    "email": "ldobrowolny1a@bloglines.com",
    "gender": "Bigender"
  }, {
    "id": 48,
    "first_name": "Niel",
    "last_name": "Stafford",
    "email": "nstafford1b@wunderground.com",
    "gender": "Male"
  }, {
    "id": 49,
    "first_name": "Boigie",
    "last_name": "Milligan",
    "email": "bmilligan1c@is.gd",
    "gender": "Male"
  }, {
    "id": 50,
    "first_name": "Arline",
    "last_name": "Hartwright",
    "email": "ahartwright1d@nyu.edu",
    "gender": "Female"
  }, {
    "id": 51,
    "first_name": "Francyne",
    "last_name": "Bony",
    "email": "fbony1e@tinyurl.com",
    "gender": "Female"
  }, {
    "id": 52,
    "first_name": "Renee",
    "last_name": "Guiu",
    "email": "rguiu1f@1688.com",
    "gender": "Female"
  }, {
    "id": 53,
    "first_name": "Erl",
    "last_name": "Goldis",
    "email": "egoldis1g@nps.gov",
    "gender": "Male"
  }, {
    "id": 54,
    "first_name": "Laurette",
    "last_name": "Neillans",
    "email": "lneillans1h@state.tx.us",
    "gender": "Female"
  }, {
    "id": 55,
    "first_name": "Yuri",
    "last_name": "Kilgallen",
    "email": "ykilgallen1i@1und1.de",
    "gender": "Male"
  }, {
    "id": 56,
    "first_name": "Arthur",
    "last_name": "Espino",
    "email": "aespino1j@posterous.com",
    "gender": "Male"
  }, {
    "id": 57,
    "first_name": "Shandie",
    "last_name": "Lackeye",
    "email": "slackeye1k@army.mil",
    "gender": "Female"
  }, {
    "id": 58,
    "first_name": "Daisey",
    "last_name": "Rushbrooke",
    "email": "drushbrooke1l@facebook.com",
    "gender": "Female"
  }, {
    "id": 59,
    "first_name": "Allyn",
    "last_name": "Heliot",
    "email": "aheliot1m@163.com",
    "gender": "Female"
  }, {
    "id": 60,
    "first_name": "Abran",
    "last_name": "Von Welldun",
    "email": "avonwelldun1n@purevolume.com",
    "gender": "Male"
  }, {
    "id": 61,
    "first_name": "Silvester",
    "last_name": "Girk",
    "email": "sgirk1o@lycos.com",
    "gender": "Male"
  }, {
    "id": 62,
    "first_name": "Marrilee",
    "last_name": "Lanfere",
    "email": "mlanfere1p@fotki.com",
    "gender": "Female"
  }, {
    "id": 63,
    "first_name": "Ingaborg",
    "last_name": "Jowle",
    "email": "ijowle1q@homestead.com",
    "gender": "Genderqueer"
  }, {
    "id": 64,
    "first_name": "Ludwig",
    "last_name": "Bosanko",
    "email": "lbosanko1r@i2i.jp",
    "gender": "Male"
  }, {
    "id": 65,
    "first_name": "Berta",
    "last_name": "Basham",
    "email": "bbasham1s@google.com.br",
    "gender": "Female"
  }, {
    "id": 66,
    "first_name": "Cindelyn",
    "last_name": "Ayars",
    "email": "cayars1t@desdev.cn",
    "gender": "Female"
  }, {
    "id": 67,
    "first_name": "Lezlie",
    "last_name": "Advani",
    "email": "ladvani1u@globo.com",
    "gender": "Female"
  }, {
    "id": 68,
    "first_name": "Meier",
    "last_name": "Hadeke",
    "email": "mhadeke1v@geocities.jp",
    "gender": "Male"
  }, {
    "id": 69,
    "first_name": "Trev",
    "last_name": "Lowdiane",
    "email": "tlowdiane1w@businessinsider.com",
    "gender": "Male"
  }, {
    "id": 70,
    "first_name": "Jaine",
    "last_name": "Hiddersley",
    "email": "jhiddersley1x@msn.com",
    "gender": "Female"
  }, {
    "id": 71,
    "first_name": "Rudolf",
    "last_name": "Carpe",
    "email": "rcarpe1y@slate.com",
    "gender": "Male"
  }, {
    "id": 72,
    "first_name": "Glennie",
    "last_name": "Dedam",
    "email": "gdedam1z@nba.com",
    "gender": "Agender"
  }, {
    "id": 73,
    "first_name": "Emalia",
    "last_name": "Thorsen",
    "email": "ethorsen20@ed.gov",
    "gender": "Female"
  }, {
    "id": 74,
    "first_name": "Terrance",
    "last_name": "Murrells",
    "email": "tmurrells21@google.pl",
    "gender": "Male"
  }, {
    "id": 75,
    "first_name": "Ravid",
    "last_name": "MacCurlye",
    "email": "rmaccurlye22@boston.com",
    "gender": "Male"
  }, {
    "id": 76,
    "first_name": "Quinton",
    "last_name": "Baudone",
    "email": "qbaudone23@bloomberg.com",
    "gender": "Male"
  }, {
    "id": 77,
    "first_name": "Cyrill",
    "last_name": "Learoid",
    "email": "clearoid24@google.ru",
    "gender": "Male"
  }, {
    "id": 78,
    "first_name": "Tabitha",
    "last_name": "McNab",
    "email": "tmcnab25@merriam-webster.com",
    "gender": "Female"
  }, {
    "id": 79,
    "first_name": "Agnola",
    "last_name": "Graith",
    "email": "agraith26@comcast.net",
    "gender": "Female"
  }, {
    "id": 80,
    "first_name": "Garland",
    "last_name": "Grieswood",
    "email": "ggrieswood27@indiatimes.com",
    "gender": "Female"
  }, {
    "id": 81,
    "first_name": "June",
    "last_name": "Hambrick",
    "email": "jhambrick28@scribd.com",
    "gender": "Female"
  }, {
    "id": 82,
    "first_name": "Nanette",
    "last_name": "Kitchaside",
    "email": "nkitchaside29@bizjournals.com",
    "gender": "Female"
  }, {
    "id": 83,
    "first_name": "Giralda",
    "last_name": "Lovelady",
    "email": "glovelady2a@ow.ly",
    "gender": "Female"
  }, {
    "id": 84,
    "first_name": "Adela",
    "last_name": "Matisoff",
    "email": "amatisoff2b@domainmarket.com",
    "gender": "Female"
  }, {
    "id": 85,
    "first_name": "Vilma",
    "last_name": "Milverton",
    "email": "vmilverton2c@themeforest.net",
    "gender": "Female"
  }, {
    "id": 86,
    "first_name": "Berkie",
    "last_name": "Brussell",
    "email": "bbrussell2d@earthlink.net",
    "gender": "Male"
  }, {
    "id": 87,
    "first_name": "Gifford",
    "last_name": "Taplow",
    "email": "gtaplow2e@lycos.com",
    "gender": "Male"
  }, {
    "id": 88,
    "first_name": "Willette",
    "last_name": "Walicki",
    "email": "wwalicki2f@sakura.ne.jp",
    "gender": "Female"
  }, {
    "id": 89,
    "first_name": "Merrill",
    "last_name": "Danihel",
    "email": "mdanihel2g@diigo.com",
    "gender": "Male"
  }, {
    "id": 90,
    "first_name": "Hendrick",
    "last_name": "Brickwood",
    "email": "hbrickwood2h@arizona.edu",
    "gender": "Male"
  }, {
    "id": 91,
    "first_name": "Ania",
    "last_name": "Krauze",
    "email": "akrauze2i@virginia.edu",
    "gender": "Female"
  }, {
    "id": 92,
    "first_name": "Spencer",
    "last_name": "Tolossi",
    "email": "stolossi2j@imdb.com",
    "gender": "Male"
  }, {
    "id": 93,
    "first_name": "Serena",
    "last_name": "Studman",
    "email": "sstudman2k@ucoz.com",
    "gender": "Female"
  }, {
    "id": 94,
    "first_name": "Bonnie",
    "last_name": "Moxley",
    "email": "bmoxley2l@google.com.hk",
    "gender": "Female"
  }, {
    "id": 95,
    "first_name": "Saul",
    "last_name": "Letcher",
    "email": "sletcher2m@vkontakte.ru",
    "gender": "Male"
  }, {
    "id": 96,
    "first_name": "Ev",
    "last_name": "Parmby",
    "email": "eparmby2n@google.it",
    "gender": "Male"
  }, {
    "id": 97,
    "first_name": "Aurel",
    "last_name": "Moston",
    "email": "amoston2o@unicef.org",
    "gender": "Female"
  }, {
    "id": 98,
    "first_name": "Dannie",
    "last_name": "Look",
    "email": "dlook2p@youtu.be",
    "gender": "Male"
  }, {
    "id": 99,
    "first_name": "Barrie",
    "last_name": "Batcheldor",
    "email": "bbatcheldor2q@amazon.com",
    "gender": "Female"
  }, {
    "id": 100,
    "first_name": "Thatcher",
    "last_name": "Woolaghan",
    "email": "twoolaghan2r@geocities.com",
    "gender": "Male"
  }]

console.table(persons);

let counter2=  100;

// SUMA 
counter2 = counter2 + 20; //120
console.log(counter2);
counter2 += 20;
console.log(counter2);

// RESTA
counter2 = counter2 - 20; //120
console.log(counter2);
counter2 -= 20;
console.log(counter2);

// DIVISION
counter2 = counter2 / 20; //120
console.log(counter2);
counter2 /= 20;
console.log(counter2);

// MULTIPLICACION
counter2 = counter2 * 20; //120
console.log(counter2);
counter2 *= 20;
console.log(counter2);